"""Update Product Constraints

Revision ID: 0d9e78616edd
Revises: ff7ae4bdc4ab
Create Date: 2026-03-03 05:12:01.605551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9e78616edd'
down_revision: Union[str, Sequence[str], None] = 'ff7ae4bdc4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_products',
    sa.Column('savings_product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('interest_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('minimum_opening_balance_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('minimum_maintaining_balance_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_application_frequency_code', sa.String(length=20), nullable=False),
    sa.Column('product_status', sa.Enum('ACTIVE', 'INACTIVE', name='enum_product_status'), nullable=False),
    sa.Column('effective_from_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint('expiry_date IS NULL OR expiry_date >= effective_from_date', name='chk_expiry_after_effective'),
    sa.CheckConstraint('interest_rate_percent >= 0.01 AND interest_rate_percent <= 50.00', name='chk_savings_product_interest_rate'),
    sa.CheckConstraint('min_age IS NULL OR max_age IS NULL OR max_age >= min_age', name='chk_age_range'),
    sa.CheckConstraint('minimum_maintaining_balance_amount >= 0', name='chk_savings_product_min_maint_balance'),
    sa.CheckConstraint('minimum_opening_balance_amount >= 0 AND minimum_opening_balance_amount <= 10000000.00', name='chk_savings_product_min_open_balance'),
    sa.PrimaryKeyConstraint('savings_product_id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_index(op.f('ix_savings_products_product_code'), 'savings_products', ['product_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_products_product_code'), table_name='savings_products')
    op.drop_table('savings_products')
    # ### end Alembic commands ###
