"""make_ages_mandatory_and_enforce_range

Revision ID: af845f214e09
Revises: 3915f7351cc2
Create Date: 2026-03-05 07:19:04.744470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af845f214e09'
down_revision: Union[str, Sequence[str], None] = '3915f7351cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings_products', 'min_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('savings_products', 'max_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings_products', 'max_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('savings_products', 'min_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
